### ISSUE TITLE
Repeat does not work with other form elements like select, textarea etc.

### ISSUE THREAD

**Issue by markxxv** [ambercouch/ac-form-field-repeater.js#1]
Why not bind to the name parameter instead of the input node for more flexibility?

**Comment by ntoscano50** [comment]
Hi @markxxv - I was looking to do the exact same thing.  If you add ":" before the input, it allows for all form elements to be updated.

**Comment by ambercouch** [comment]
Only four years later. Just fix this issue in the last push! FTW
